### PR TITLE
Latest Release

### PR DESCRIPTION
**Pull request by dmessing**
Merging in bugs for AP-68 and AP-67 and AP-69 

@thabofletcher these are the utm fixes

### CODE REVIEW

**Comment by thabofletcher** [comment]
@callmekatootie @dmessing I'm a little unsure about his method of saving the query parameters, referencing the query params, and doing state changes. It seems very non standard, and I was wondering why we can't use $stateParams, $state.go, and saving the utm params in a variable rather than using cookies or local storage? I'm not opposed to making some hacks when necessary, but please comment why it has to be done in a non standard why in the code so people reading it later can understand.

**Comment by dmessing** [comment]
Any chance we  can move this forward but then clean up?  We have ad spend going today.

**Comment by callmekatootie** [comment]
@thabofletcher Check out issue 202 in the angular ui router repo. I would have pasted the url here but it would get linked and everyone would be able to see so dropped that.

Anyway, when using angular ui router, that is, when using the states and the stateparams, the query params should be present in the url definition.

Since, in your scenario, you want the query params, particularly, the utm_* ones to exist for all urls, this would mean that we would need to append the utm_* query params to each existing url definition.
When you add new urls, you would also have to carry this out again - in my opinion, this would be a very poor way of achieving this.

`stateParams` will only come into picture when the url definition itself contains the query params. But in this case, we do not have the query params in the url definition (we SHOULD NOT have the query params in the url definition - this would force us to have it for all urls which is incorrect)

What I have done in this case is made use of `$location.search()` - this is the standard way to doing it, NOT a hack.  In fact, if it weren't for angular ui router, this would be the correct way to carry it out.

**Comment by thabofletcher** [comment]
Thanks for explaining. Understood, you are using location.search() to avoid having to define those params on each route. And the line originalQuery.params = $location.search() is about persisting params as you move around?

Last question, was there a bug with state.go that caused you to use:
if (!$scope.$$phase) $scope.$apply () -> ($location.path GO_TO_STATE) .search('regsuccess', 'true')

**Comment by callmekatootie** [comment]
Correct. originalQuery.params is used to persist the params when the route
changes.

As for the code that you pointed out, since I needed to pass query params
not defined in the route definition, I could not make use of $state.go. I
used $location.path instead. When I tested it, it was not being called
during the digest cycle. (Dunno why). So, I added $scope.$apply and changed
the path inside this.

Later, I was told that adding that caused the test to fail. Turns out that
the test also uses $scope.$apply which throws the error when my code also
triggers the digest cycle.

Thus, I added the additional check - if we are not in digest cycle, trigger
it and change path. Else, don't.

**Comment by thabofletcher** [comment]
Cool, makes sense, thanks for clearing that up.

**Pull request merged**
